### ISSUE TITLE
IA data missing for latest day 

### ISSUE THREAD

**Issue by CovidCountyUSA** [covid-projections/covid-data-public#213]
Problem:  Iowa county data for all counties for latest day..
File: county csv file pulled from api
Scope:  the entire record(s) (i.e. date) for the latest day is missing e.g. if today is 3/4/2021 the records for 3/3/2021 are missing.  This has been happening for at least 3 days.

**Comment by BrettBoval** [comment]
Iowa had stopped reporting county-level positive cases, and was only reporting positive tests.

We've switched to a different data provider (USAFacts) for county level case data in Iowa while we work with our upstream data providers to get that back online in our primary data source.
