### ISSUE TITLE
Debug DC, Nevada and Nebraska having no hospitalization data and empty projections on staging

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-data-public#36]

**Comment by igorkofman** [comment]
Snapshots affected 192, 194

**Comment by davidstrauss** [comment]
The affected regions all seem to have quoted "NaN" values in the final columns of the inner arrays:

```["0", "03/03/20", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "7279", "0", "0.0", "0.0", "0", "0", "0", "0", "NaN", "NaN"]```

**Comment by davidstrauss** [comment]
Those last two columns are vestigial; they do not carry actual data at this point. Yet, the quoted "NaN" values are really interesting for a couple reasons:

- Some JSON dump tools render a Python NaN float value (common in Pandasa) as `NaN` in exported JSON.
- `NaN` is not actually valid JSON, so some tools respond by assuming it's a string missing quotes.
- We usually try to either map NaN to `null` in JSON via simplejson's `ignore_nan=True` or by using `.fillna()` on a DataFrame prior to JSON export.
