### ISSUE TITLE
Document data pipeline.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-public#7]
Need to write up a document describing:

1. How do we suck data in (i.e. this covid-data-public repo)
2. How do we suck that data into our models (i.e. point covid-data-model at a version of the covid-data-public repo).
3. How do we suck the data and models into the website (e.g. by publishing to data.covidactnow.org and pointing the website at the new version).

**Comment by davidstrauss** [comment]
@jredding You worked on some diagrams for this after we talked. How should we publish them?
