### ISSUE TITLE
Consume NACo intervention data.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-public#8]
Write a script that pulls from https://ce.naco.org/python/data?dbset=COVID_Table&dbind=County_Declaration_Type3|County_Emergency_Declaration|County_Shelter_In_Place_Policy|County_Business_Closure_Policy|Population_total|Population_over_65_pct&dbyear=2020

and spits out a county_interventions.json file similar to our existing state one (currently here: https://github.com/covid-projections/covid-projections/blob/develop/src/assets/data/interventions.json but will be moving into this repo, see #5)

Their data looks like this:

```
{
    "columns": [
        "FIPS",
        "County_Declaration_Type3",
        "County_Emergency_Declaration",
        "County_Shelter_In_Place_Policy",
        "County_Business_Closure_Policy",
        "Population_total",
        "Population_over_65_pct"
    ],
    "data": [
        [
            "02020",
            "Both Policies",
            "Declared March 16, <a target=\"_blank\" href=\"https://www.muni.org/covid-19/Pages/default.aspx\" style=\"color: #92D0F9\">Link</a>",
            "Declared March 20, <a target=\"_blank\" href=\"https://www.muni.org/departments/mayor/pressreleases/documents/eo-03.pdf\" style=\"color: #92D0F9\">Link</a>",
            null,
            291538.0,
            0.1109049246
        ],
        ...
    ]
}
```

A non-null County_Shelter_In_Place_Policy should map to "shelter_in_place" in the resulting interventions file.

I am thinking a non-null County_Emergency_Declaration or County_Business_Closure_Policy should map to "social_distancing" but we can revisit / tweak this. So we would output:
```
{
    "02020": "social_distancing",
    ...
}
```

I think the downloader should probably live in scripts/update-interventions-naco.py and output to data/interventions-naco/

**Comment by tsebens** [comment]
Is it a problem if we store it as a .csv? I'm assuming that this data is going to be ingested by the model, and it would be easier to do so if we wrote it to a csv file.

**Comment by gsoltis** [comment]
We can maybe do both. I think the webapp currently expects json, but csv would definitely be easier for the dod pipeline

**Comment by tsebens** [comment]
Actually, I think I misunderstood the nature of the data. The intervention data is stored in what is essentially JSON

**Comment by mikelehen** [comment]
Yeah.  It needs to be JSON for the website to consume it.  But we can store it as both if it makes things easier for some reason.

**Comment by tsebens** [comment]
How should we convert their values into r values? Currently our interventions take the following form:
```
{ 
    4/1/2020: 1.7,
    4/16/2020: 1.4,
    4/24/2020: 1.2
}
```
A dict with dates as keys and an r value. So we need to take the data they're giving us and convert it into an r value. I think we'll need Max and his team to weigh in on this conversation

**Comment by tsebens** [comment]
Also, is it acceptable to roll the NACo data into the current update script pattern? That would mean adding the update logic to the udpate.py script and adding a flag that can be passed to specify the NACo data.
